### ISSUE TITLE
有没有通过抖音ID，获取用户所有视频的爬虫

### ISSUE THREAD

**Issue by cnbillow** [moyada/stealer#10]
找了很多，好像都不可以。

**Comment by moyada** [comment]
我因为自己不需要就没做，我记得有人做过，通过用户分享的链接爬取，原来我分析过，也是可行的，除非也被修改了。。。

**Comment by xuyang7952** [comment]
> 找了很多，好像都不可以。
找到了吗？我也在找下载抖音视频的
