### ISSUE TITLE
抖音解析不了

### ISSUE THREAD

**Issue by yuandoudou928** [moyada/stealer#103]
抖音解析不了，提示：“作品信息错误”
分享连接：5.12 VLw:/ 在北极我没有对手，离开北极也一样.# 北极熊 # 野生动物零距离  https://v.douyin.com/iepGU5Xf/ 复制此链接，打开Dou音搜索，直接观看视频！

**Comment by aslanTT** [comment]
+1 解析失败了

**Comment by Lw1244204021** [comment]
+1，8月份还能用

**Comment by moyada** [comment]
暂时没时间更新，这块逻辑得重构，现在只能从接口拿
