### ISSUE TITLE
你好，请问 data = v["aweme"]  = None, 是我需要配置什么文件吗？？？

### ISSUE THREAD

**Issue by zhz-we** [moyada/stealer#108]
![image](https://github.com/moyada/stealer/assets/42529417/454215ea-c00b-42c5-90a3-c839dd91d38c)

![image](https://github.com/moyada/stealer/assets/42529417/54f5070f-4b11-4c39-8b79-3306c636156b)

**Comment by moyada** [comment]
网页端只能通过 https://www.douyin.com/aweme/v1/web/aweme/detail/ 获取
