### ISSUE TITLE
快手还能用吗？

### ISSUE THREAD

**Issue by howellhux** [moyada/stealer#109]
好像解析不了了，api接口经常报参数错误
https://v.kuaishou.com/imBpXt

**Comment by howellhux** [comment]
请大佬帮我看看我下面的代码，为何返回的总是{"result":21,"error_msg":"参数格式错误，请仔细阅读API文档"}

headers = {
        'Accept': '*/*', 
        'Accept-Encoding': 'gzip, deflate, br', 
        'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1',
        'Cookie': 'did=web_9bceee20fa5d4a968535a27e538bf51b; didv=1655992503000;',
        'Origin': 'https://v.m.chenzhongtech.com', 
        'Referer': locs,
        'Sec-Ch-Ua': '"Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"', 
        'Sec-Fetch-User': '?1',
        'Sec-Fetch-Site': 'same-origin', 
        'Sec-Fetch-Dest': 'empty', 
        'Sec-Fetch-Mode': 'cors', 
        'Content-Type': 'application/json'
    }

    post_data = {
            "fid": query_parameters.get("fid")[0],
            "shareToken": query_parameters.get("shareToken")[0],
            "shareObjectId": query_parameters.get("shareObjectId")[0],
            "shareMethod": "TOKEN",
            "shareId": query_parameters.get("shareId")[0],
            "shareResourceType": "PHOTO_OTHER",
            "shareChannel": "share_copylink",
            "kpn": "KUAISHOU",
            "subBiz": "BROWSE_SLIDE_PHOTO",
            "env": "SHARE_VIEWER_ENV_TX_TRICK",
            "h5Domain": "v.m.chenzhongtech.com",
            "photoId": query_parameters.get("photoId")[0],
            "isLongVideo": False,
        }
    
    async with aiohttp.ClientSession() as session:
        async with session.post('https://v.m.chenzhongtech.com/rest/wd/photo/info?kpn=KUAISHOU&captchaToken=', data=post_data, headers=headers) as response:
            print(response.status)
            content = await response.read()
            print(content.decode())

**Comment by howellhux** [comment]
可以用了，谢谢大佬，是我代码的问题

**Comment by zcc19960910** [comment]
> 可以用了，谢谢大佬，是我代码的问题

麻烦加一下我微信，交流下15603650608

**Comment by moyada** [comment]
修复了，快手网页端分享的有变动
