### ISSUE TITLE
大佬，皮皮虾的解析又不行了，取不出来了

### ISSUE THREAD

**Issue by smalloneSAMA** [moyada/stealer#21]
`url = data['data']['item']['comments'][0]['item']['video']['video_high']['url_list'][0]['url']`
这一段现在取出来的url为空了，comments字段下没有数据了

**Comment by moyada** [comment]
好了，他们的数据结构一直在变化

**Comment by vsdfnvuitsb** [comment]
> 好了，他们的数据结构一直在变化

老板您好皮皮虾的解析失效了

**Comment by moyada** [comment]
已修复
