### ISSUE TITLE
希望可以增加 哔哩哔哩

### ISSUE THREAD

**Issue by ArthurK2** [moyada/stealer#41]
API地址  https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/videostream_url.md

**Comment by moyada** [comment]
> https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/videostream_url.md

可以的，试了下这个API带水印的就是

**Comment by ArthurK2** [comment]
> > > > https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/videostream_url.md
> > > 
> > > 
> > > 可以的，试了下这个API带水印的就是
> > 
> > 
> > 因为b站水印是硬编进视频的，能下载就行，水印无所谓 😂 就算是在 App 里面看也是直接带水印播放的 b站除非投非自制，要不然都会把水印硬编码进视频里面，没法去的
> 
> 好了你可以看看，我只用了些短视频测试 `core/config` 里面可以配置cookie，当然不配也行

感谢  😊
