### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by f627422467** [moyada/stealer#5]
安装vue依赖时，报错。这个是有什么版本要求吗？

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appfront@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appfront@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by moyada** [comment]
build 路径给排除了。。。develop 分支上你先看看，有些依赖要安装

**Comment by f627422467** [comment]
好的，我试试先
