### ISSUE TITLE
抖音获取高清晰度无水印视频

### ISSUE THREAD

**Issue by laodiaoyadashu** [moyada/stealer#52]
作者你好，我发现抖音的视频直链是拼接来的，其实我看抖音的web api中响应中已经包含了视频直链。
例：https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=7087453974684552463
api结果：
```json
"play_addr": {
                    "uri": "v0d00fg10000c9dr3lbc77u02ekjgamg",
                    "url_list": [
                        "https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v0d00fg10000c9dr3lbc77u02ekjgamg&ratio=720p&line=0"
                    ]
                }
```
该视频的直链就是`https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v0d00fg10000c9dr3lbc77u02ekjgamg&ratio=720p&line=0`，但这条链接是有水印的，只需把链接中的playwm替换为play即可去掉水印。

**Comment by moyada** [comment]
这个我是知道的，他们两个的功能是一样的，其实获取的方式有很多，效果都是一样
