### ISSUE TITLE
action cicd 每次提交自动编译(或者手动点)提交镜像到docker仓库

### ISSUE THREAD

**Issue by pycgo** [moyada/stealer#54]
1、现在文档里面的镜像跑了有点问题
```
docker run -itd --name st1 xueyikang/stealer:1.1.0
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```
2、通过最新的git clone 下 build 出来的镜像可以正常跑

所以我想是不是搞个action 自动编译 利用github的action
以后直接拉这个最新的就行了 默认tag就是latest 可以不写
docker run -itd --name stealer xueyikang/stealer

旧的环境可以先docker pull xueyikang/stealer  然后再docker run -itd --name stealer xueyikang/stealer  确保镜像最新

如果需要我可以提交一个带docker密码变量的action文件 但需要作者大大到action 配置密码凭据的环境变量。

**Comment by pycgo** [comment]
也可以参考这个文件直接写https://github.com/pycgo/tools/blob/master/.github/workflows/docker-image.yml

变量设置可以参考图
![image](https://user-images.githubusercontent.com/55949132/165482238-57d06fe5-f59e-4e0f-9d18-ac7866d12ccd.png)

**Comment by moyada** [comment]
谢谢，我去配置下，我docker玩的不多
