### ISSUE TITLE
b站的解出来的地址403了

### ISSUE THREAD

**Issue by mengxingxinqing** [moyada/stealer#57]
b站的解出来的地址403了 https://b23.tv/DzJqBDR  https://upos-sz-mirrorcoso1.bilivideo.com/upgcxcode/62/51/717695162/717695162-1-64.flv?e=ig8euxZM2rNcNbRVhwdVhwdlhWdVhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1652328107&gen=playurlv2&os=coso1bv&oi=795806359&trid=077e726525d84ef3b5238e063b5040dfu&platform=pc&upsig=b888378b95ece4fbc431db7f1fd42f7c&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=92275&logo=80000000

**Comment by moyada** [comment]
你是直接拿url打开的是吧，b站对请求头有做防御性校验，可以参考下代理里的配置
