### ISSUE TITLE
live.kuaishou.com links

### ISSUE THREAD

**Issue by astandarduser** [moyada/stealer#6]
The v.kuaishou.com seems to be broken. It would be amazing to have support for links in this format       https://live.kuaishou.com/u/xiaoxing/3xrqujnseqmz4zm

**Comment by moyada** [comment]
Can you provide a broken link like [https://v.kuaishou.com/76qrJG](https://v.kuaishou.com/76qrJG)? If you need to check, you can open it in a mobile browser.
