### ISSUE TITLE
快手iOS移动端复制出来的视频链接无法下载

### ISSUE THREAD

**Issue by HapCoderWei** [moyada/stealer#64]
大佬好，我从iOS的快手app中复制视频分享链接，然后使用工具下载的时候提示地址分析失败，无法获取到视频的原地址。麻烦看下可能是什么原因导致的，谢谢🙏。
抖音的视频解析功能我试了是可以用的

我复制的链接：
https://v.kuaishou.com/jpEWZw "我是快手时尚种草官 "防蓝光防辐射的老花镜 "时尚老花镜 复制此消息，打开【快手】直接观看！

**Comment by i8sn0w** [comment]
现在可能就不行了，应该是服务端接口或者字段格式改了

**Comment by moyada** [comment]
哈哈，看了下它们的逻辑变了，爬的人太多了吧。过段我来更新，不过我这里浏览来源有它们官方的，可能还会被改

**Comment by moyada** [comment]
已经修复
