### ISSUE TITLE
皮皮虾有水印

### ISSUE THREAD

**Issue by 17337162621254271304** [moyada/stealer#84]
分享地址：https://h5.pipix.com/s/A9gx4po/
解析后地址：http://v6-cdn-tos.ppxvod.com/1854b28cc5a0fc3353918df2bdaeea76/642ba73c/video/tos/cn/tos-cn-ve-0076/3b65070adc4f4043857ce164db2dae15/?a=1319&ch=0&cr=0&dr=3&lr=superb&cd=0%7C0%7C1%7C0&cv=1&br=1192&bt=1192&cs=0&ds=3&eid=2048&ft=4zerVjjM9TpxeFqoZmCTeK_ScoApMhbI6vrKo~h0D2o0g3&mime_type=video_mp4&qs=0&rc=N2U5OTYzPGg8Omc0MzQ0aUBpMzs0O2c6ZnltZzMzNGYzM0AzMDAzMTYzNmAxYDA1YWEzYSNqNGJzcjRnMmFgLS1kMWFzcw%3D%3D&l=20230404112735AD56D679C8D2A5BC57C8&btag=8000
皮皮虾app中看视频没水印，下载后有水印
<img width="979" alt="image" src="https://user-images.githubusercontent.com/32665103/229680048-a7cb4750-77fb-4bd1-be1e-f4fcfc8c9157.png">

**Comment by moyada** [comment]
那得抓一下app接口，我现在没设备，你有抓到可以发出来

**Comment by 17337162621254271304** [comment]
关了。有的有水印是因为原视频被下载多次，本身已带水印

**Comment by 17337162621254271304** [comment]
关了。有的有水印是因为原视频被下载多次，本身已带水印
