### ISSUE TITLE
b站解析链接403forbidden，西瓜视频解析失效

### ISSUE THREAD

**Issue by Lw1244204021** [moyada/stealer#95]

**Comment by Lw1244204021** [comment]
b站：
url：https://www.bilibili.com/video/BV17s411P7oi?p=5&share_source=copy_web
解析出的视频链接：https://upos-sz-estgoss.bilivideo.com/upgcxcode/04/95/49869504/49869504_da2-1-16.mp4?e=ig8euxZM2rNcNbRVhwdVhwdlhWdVhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1691225160&gen=playurlv2&os=upos&oi=1966932890&trid=d0aecd5970024624b8e8d4a6787c0755u&mid=0&platform=pc&upsig=b40bca54e07da549982a99e11626f0be&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&buvid=&build=0&agrr=1&bw=53229&logo=80000000

**Comment by Lw1244204021** [comment]
西瓜视频模仿你的写了一段代码：
from tools import http_utils
import re
from core import config
from typing import Optional

url = 'https://www.ixigua.com/7249686811810005539'
url = 'https://www.ixigua.com/7237058133238120975'
headers = {
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en,zh-CN;q=0.9,zh;q=0.8,de;q=0.7",
    "user-agent": config.user_agent
}
download_headers = {
    "accept": "*/*",
    "accept-encoding": "identity;q=1, *;q=0",
    "host": "jsmov2.a.yximgs.com",
    "range": "bytes=0-",
    "sec-fetch-dest": "video",
    "sec-fetch-mode": "no-cors",
    "sec-fetch-site": "cross-sit",
    "user-agent": config.user_agent
}


def get_prefix_pattern() -> str:
    return 'ixigua\.com\/'


def make_url(index) -> str:
    return 'https://www.ixigua.com/' + index


def get_url(text: str) -> Optional[str]:
    urls = re.findall(r'(?<=' + get_prefix_pattern() + ')\w+', text, re.I | re.M)
    if urls:
        return make_url(urls[0])
    return None


url = get_url(url)
print(url)
res = http_utils.get(url, header=headers)
print(res)
html = str(res.content)
print(html)
url = re.findall(r"(?<=type=\"video\/mp4\" src=\")(.*?)(?=\")", html)[0]
print(url)


--------------------报错：
Traceback (most recent call last):
  File "***\test.py", line 47, in <module>
    url = re.findall(r"(?<=type=\"video\/mp4\" src=\")(.*?)(?=\")", html)[0]
IndexError: list index out of range

**Comment by moyada** [comment]
b站接口改了没有高清mp4，我重做了你可以试试
西瓜早没维护了，你测了没问题可以提上来
