### ISSUE TITLE
抖音下载的视频，是0字节，播放不了

### ISSUE THREAD

**Issue by goforu** [moyada/stealer#97]
4.84 Tyg:/ 中国“哥谭”往事，毒贩杀警察、烧警车，疯狂拘捕。# 电影绝地追击  https://v.douyin.com/iJWSF9Kw/ 复制此链接，打开Dou音搜索，直接观看视频！
<img width="859" alt="image" src="https://github.com/moyada/stealer/assets/5236864/425bcbf8-1f58-4ef8-b6f6-11a5bb1edd5a">

**Comment by moyada** [comment]
这种一般是被风控了
